name: erestro
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.13+14

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^2.0.1
  http: ^1.2.0
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.1.4
  cached_network_image: ^3.2.0
  firebase_core: ^3.3.0
  country_code_picker: ^3.0.0
  flutter_stripe: ^11.5.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  url_launcher: ^6.1.2
  sms_autofill: ^2.2.0
  image_picker: ^1.0.8
  fl_chart: ^0.69.0 
  file_picker: ^8.0.7
  flutter_local_notifications: ^17.1.1
  firebase_messaging: ^15.0.4
  sticky_headers: ^0.3.0+2
  flutter_html: ^3.0.0-alpha.6
  html_editor_enhanced: ^2.4.0+1
  google_maps_flutter: ^2.1.5
  dio: ^5.3.2
  geocoding: ^3.0.0
  mime: ^1.0.2
  flutter_html_to_pdf:
    git:
      url: https://github.com/SiddhiChauhan6227/flutter_html_to_pdf2.git
  permission_handler: ^11.3.1
  open_filex: ^4.3.2
  geolocator: ^13.0.1
  external_path: ^2.2.0
  path_drawing: ^1.0.1
  change_app_package_name: ^1.4.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  intl: ^0.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/gif/
    - lib/Language/
    

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-Regular.ttf
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/font/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
